name: "[Auto] update bangumi version"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches:
    - main

jobs:
  AutoUpdateBangumi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      run: |

        latestVersion=$(curl --silent "https://api.github.com/repos/czy0729/Bangumi/releases/latest" | jq ."tag_name")
        latestIPAUrl="https://github.com/czy0729/Bangumi/releases/download/${latestVersion}/bangumi_${latestVersion}_archive.ipa"
        whatsnew=$(curl --silent "https://api.github.com/repos/czy0729/Bangumi/releases/latest" | jq ."body")
        statusCode=$(curl --silent --head -w "%{http_code}\n" "$latestIPAUrl" -o /dev/null)

        if [ true ]; then
          jq --null-input \
            --arg latestVersion $latestVersion \
            --arg whatsnew $whatsnew \
            --arg latestIPAUrl $latestIPAUrl  \
            '{ "name": "Bangumi", "identifier": "tv.bangumi.czy0729", "apps": [{ "beta": false, "name": "Bangumi", "bundleIdentifier": "tv.bangumi.czy0729", "developerName": "czy0729", "subtitle": "Bangumi", "version": $latestVersion, "versionDate": "2022-08-29T11:21:00+02:00", "versionDescription": $whatsnew, "downloadURL": $latestIPAUrl, "localizedDescription": "An unofficial https://bgm.tv app client for Android and iOS, built with React Native", "iconURL": "https://raw.githubusercontent.com/czy0729/Bangumi/master/src/assets/images/icon.png", "tintColor": "9b54fd", "size": 120583721, "screenshotURLs": ["https://user-images.githubusercontent.com/13514316/171143439-5e9c6c22-889d-4774-8c66-4316294d5019.png","https://user-images.githubusercontent.com/13514316/171143470-a982f725-2b86-4c8a-b1a3-f3a3b2b13060.png","https://user-images.githubusercontent.com/13514316/171143473-6589f342-9ff3-4f56-b2e4-9d6e1dfd15ca.png"] }] }' \
            >  ${GITHUB_WORKSPACE}/bangumi.json
        fi
        

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        branch: update-bangumi
        title: '[Auto] Update bangumi'
        body: |
          Update report
          - Updated with Bangumi Version
          - Auto-generated

